
export interface Review {
  id: string;
  name: string;
  countryCode: string;
  countryName: string;
  rating: number;
  text: string;
  timeAgo: string;
}

export const REVIEWS: Review[] = [
  // USA (20)
  { id: 'us-1', name: 'James Anderson', countryCode: 'US', countryName: 'USA', rating: 5, text: '“My friend literally thought I was joking when I said the app was this smooth.” 😂', timeAgo: '2 days ago' },
  { id: 'us-2', name: 'Michael Carter', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I still check every day to make sure the consistency remains the same.” 👀', timeAgo: '1 week ago' },
  { id: 'us-3', name: 'Daniel Walker', countryCode: 'US', countryName: 'USA', rating: 4, text: '“The interface just feels comfortable to use honestly.”', timeAgo: '3 weeks ago' },
  { id: 'us-4', name: 'Ethan Brooks', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I expected unnecessary complications but everything was straightforward.” ✅', timeAgo: '1 month ago' },
  { id: 'us-5', name: 'Ryan Mitchell', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The support guy explained things better than I expected.” 👍', timeAgo: '2 months ago' },
  { id: 'us-6', name: 'Sophia Johnson', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I’m still cautious but so far I can’t complain.”', timeAgo: '3 months ago' },
  { id: 'us-7', name: 'Emily Parker', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I tested it with a small amount first because online trust is hard these days.” 💭', timeAgo: '4 months ago' },
  { id: 'us-8', name: 'Olivia Morgan', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The dashboard is clean without trying too hard.” ✨', timeAgo: '5 months ago' },
  { id: 'us-9', name: 'Charlotte Evans', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I didn’t even need help finding my way around.”', timeAgo: '6 months ago' },
  { id: 'us-10', name: 'Ava Thompson', countryCode: 'US', countryName: 'USA', rating: 5, text: '“Most platforms overwhelm me but this one feels calm.” 😌', timeAgo: '7 months ago' },
  { id: 'us-11', name: 'Benjamin Harris', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I kept delaying joining until my colleague showed me his experience.”', timeAgo: '8 months ago' },
  { id: 'us-12', name: 'Matthew Collins', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The app runs smoother than some banking apps honestly.” 📱', timeAgo: '9 months ago' },
  { id: 'us-13', name: 'Christopher Reed', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I’m watching long term before getting too comfortable.” ⏳', timeAgo: '10 months ago' },
  { id: 'us-14', name: 'Nathan Cooper', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The whole thing feels professionally arranged.”', timeAgo: '11 months ago' },
  { id: 'us-15', name: 'Alexander White', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I was expecting delayed withdrawals but mine came through normally.” 💸', timeAgo: '1 year ago' },
  { id: 'us-16', name: 'Grace Wilson', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The support team deserves some credit honestly.”', timeAgo: '1 year ago' },
  { id: 'us-17', name: 'Victoria Lewis', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I thought people were overhyping it at first.” 🤨', timeAgo: '1 year ago' },
  { id: 'us-18', name: 'Madison Clark', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The experience has been stress free for me so far.”', timeAgo: '1 year ago' },
  { id: 'us-19', name: 'Abigail Scott', countryCode: 'US', countryName: 'USA', rating: 5, text: '“Everything updates surprisingly fast.” ⚡', timeAgo: '2 years ago' },
  { id: 'us-20', name: 'Hannah Rivera', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The registration process didn’t give me a headache.”', timeAgo: '2 years ago' },

  // UK (20)
  { id: 'uk-1', name: 'Oliver Smith', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I appreciate how simple everything looks.”', timeAgo: '2 days ago' },
  { id: 'uk-2', name: 'George Williams', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I’ve had enough bad experiences online to stay careful.” 👀', timeAgo: '1 week ago' },
  { id: 'uk-3', name: 'Harry Brown', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The app feels polished without looking too complicated.”', timeAgo: '3 weeks ago' },
  { id: 'uk-4', name: 'Jack Taylor', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“I only joined after seeing people around me use it consistently.” 👌', timeAgo: '1 month ago' },
  { id: 'uk-5', name: 'Thomas Davies', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The navigation feels natural.”', timeAgo: '2 months ago' },
  { id: 'uk-6', name: 'Amelia Wilson', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I honestly expected support to disappear after registration.” 😅', timeAgo: '3 months ago' },
  { id: 'uk-7', name: 'Isla Johnson', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The transaction process feels smooth every time.”', timeAgo: '4 months ago' },
  { id: 'uk-8', name: 'Sophie Walker', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“The app actually looks maintained.”', timeAgo: '5 months ago' },
  { id: 'uk-9', name: 'Freya Thompson', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I like how beginner friendly the interface feels.” 👍', timeAgo: '6 months ago' },
  { id: 'uk-10', name: 'Charlotte Evans', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“Still observing quietly before I fully trust it.”', timeAgo: '7 months ago' },
  { id: 'uk-11', name: 'Henry Roberts', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“Everything just works the way it should.” ✅', timeAgo: '8 months ago' },
  { id: 'uk-12', name: 'Edward Hughes', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“I was prepared for stress but surprisingly didn’t get any.”', timeAgo: '9 months ago' },
  { id: 'uk-13', name: 'William Turner', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The loading speed is one of the first things I noticed.” ⚡', timeAgo: '10 months ago' },
  { id: 'uk-14', name: 'Arthur Collins', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I appreciate how organized the dashboard feels.”', timeAgo: '11 months ago' },
  { id: 'uk-15', name: 'Leo Morgan', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“It’s refreshing to use something that isn’t confusing.”', timeAgo: '1 year ago' },
  { id: 'uk-16', name: 'Emily Scott', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“My cousin kept recommending it until I finally tried.” 😂', timeAgo: '1 year ago' },
  { id: 'uk-17', name: 'Jessica Parker', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The app experience has been stable for me.”', timeAgo: '1 year ago' },
  { id: 'uk-18', name: 'Lucy Cooper', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I’m not someone who rushes into platforms like this.”', timeAgo: '1 year ago' },
  { id: 'uk-19', name: 'Mia Richardson', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“The support responses feel human and respectful.” 👏', timeAgo: '2 years ago' },
  { id: 'uk-20', name: 'Ella Bennett', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I like that the interface isn’t overcrowded.”', timeAgo: '2 years ago' },

  // Singapore (20)
  { id: 'sg-1', name: 'Ethan Tan', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The onboarding process felt smoother than expected.” ✨', timeAgo: '2 days ago' },
  { id: 'sg-2', name: 'Ryan Lim', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I still have trust issues generally, but so far things look okay.”', timeAgo: '1 week ago' },
  { id: 'sg-3', name: 'Daniel Wong', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The app works perfectly fine on my device.” 📱', timeAgo: '3 weeks ago' },
  { id: 'sg-4', name: 'Marcus Lee', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“I appreciate that everything is clearly arranged.”', timeAgo: '1 month ago' },
  { id: 'sg-5', name: 'Jason Koh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The design gives a premium feeling honestly.” 💎', timeAgo: '2 months ago' },
  { id: 'sg-6', name: 'Cheryl Ong', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I joined quietly just to test things for myself.”', timeAgo: '3 months ago' },
  { id: 'sg-7', name: 'Rachel Tan', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“Everything has been straightforward so far.”', timeAgo: '4 months ago' },
  { id: 'sg-8', name: 'Grace Lim', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“The transaction history section is easy to understand.” 📊', timeAgo: '5 months ago' },
  { id: 'sg-9', name: 'Amanda Chua', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I expected hidden stress but didn’t really encounter any.”', timeAgo: '6 months ago' },
  { id: 'sg-10', name: 'Michelle Ng', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The app feels very modern.”', timeAgo: '7 months ago' },
  { id: 'sg-11', name: 'Adrian Goh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“So far the consistency has been decent.” 👍', timeAgo: '8 months ago' },
  { id: 'sg-12', name: 'Brandon Teo', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“The support team answered my questions faster than expected.”', timeAgo: '9 months ago' },
  { id: 'sg-13', name: 'Nicole Seah', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I’m still monitoring things carefully.” 👀', timeAgo: '10 months ago' },
  { id: 'sg-14', name: 'Vanessa Yeo', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The platform feels easier than most others I’ve tested.”', timeAgo: '11 months ago' },
  { id: 'sg-15', name: 'Kevin Ang', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I honestly didn’t expect to like the interface this much.” 🔥', timeAgo: '1 year ago' },
  { id: 'sg-16', name: 'Sophia Ho', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“The mobile version feels smooth.”', timeAgo: '1 year ago' },
  { id: 'sg-17', name: 'Darren Loh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I appreciate how responsive everything feels.”', timeAgo: '1 year ago' },
  { id: 'sg-18', name: 'Jasmine Quek', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“It’s one of the cleaner dashboards I’ve seen.” ✨', timeAgo: '1 year ago' },
  { id: 'sg-19', name: 'Terence Yap', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“I’ve had no issues navigating around the app.”', timeAgo: '2 years ago' },
  { id: 'sg-20', name: 'Clarissa Toh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The simplicity makes a big difference honestly.”', timeAgo: '2 years ago' },

  // Australia (20)
  { id: 'au-1', name: 'Oliver Jones', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Reliable node execution and transparent reporting.”', timeAgo: '2 days ago' },
  { id: 'au-2', name: 'Charlotte Smith', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“The neural clusters provide a unique advantage.”', timeAgo: '1 week ago' },
  { id: 'au-3', name: 'Jack Davies', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Sophisticated platform with impressive yield.”', timeAgo: '3 weeks ago' },
  { id: 'au-4', name: 'Amelia Wilson', countryCode: 'AU', countryName: 'Australia', rating: 4, text: '“Premium experience throughout. Highly effective.”', timeAgo: '1 month ago' },
  { id: 'au-5', name: 'William Taylor', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Institutional grade security meets modern tech.”', timeAgo: '2 months ago' },
  { id: 'au-6', name: 'Mia Brown', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Seamless asset orchestration. My top choice.”', timeAgo: '3 months ago' },
  { id: 'au-7', name: 'Thomas Evans', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“The daily ROI updates keep you engaged.”', timeAgo: '4 months ago' },
  { id: 'au-8', name: 'Olivia Thomas', countryCode: 'AU', countryName: 'Australia', rating: 4, text: '“CGA Trades delivers on its promise of excellence.”', timeAgo: '5 months ago' },
  { id: 'au-9', name: 'Henry Roberts', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“The regular node activation was easy.”', timeAgo: '6 months ago' },
  { id: 'au-10', name: 'Chloe Johnson', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Superior tech and superior support.”', timeAgo: '7 months ago' },
  { id: 'au-11', name: 'Samuel Walker', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Fast withdrawals and great support.”', timeAgo: '8 months ago' },
  { id: 'au-12', name: 'Grace Wright', countryCode: 'AU', countryName: 'Australia', rating: 4, text: '“Seamless experience from signup.”', timeAgo: '9 months ago' },
  { id: 'au-13', name: 'Benjamin Green', countryCode: 'AU', countryName: 'Australia', rating: 4, text: '“The security protocols give me peace.”', timeAgo: '10 months ago' },
  { id: 'au-14', name: 'Emily Hughes', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Impressive yields and transparent ops.”', timeAgo: '11 months ago' },
  { id: 'au-15', name: 'Daniel Hall', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Good platform for institutional grade.”', timeAgo: '1 year ago' },
  { id: 'au-16', name: 'Sophie Lewis', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“CGA Trades is the future of wealth.”', timeAgo: '1 year ago' },
  { id: 'au-17', name: 'Lucas Harris', countryCode: 'AU', countryName: 'Australia', rating: 4, text: '“The regular plan is perfect.”', timeAgo: '1 year ago' },
  { id: 'au-18', name: 'Lily Martin', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Exceptional service and rewarding.”', timeAgo: '1 year ago' },
  { id: 'au-19', name: 'Lachlan Ross', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“Finally a platform that delivers.”', timeAgo: '2 years ago' },
  { id: 'au-20', name: 'Zoe Campbell', countryCode: 'AU', countryName: 'Australia', rating: 5, text: '“The user experience is premium.”', timeAgo: '2 years ago' },

  // United Arab Emirates (20)
  { id: 'ae-1', name: 'Faisal Al-Mansoori', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The onboarding process was much smoother than I expected.”', timeAgo: '2 days ago' },
  { id: 'ae-2', name: 'Amna Al-Hashimi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“I joined quietly just to test things for myself.”', timeAgo: '1 week ago' },
  { id: 'ae-3', name: 'Tariq Al-Suwaidi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The app works perfectly fine on my device.”', timeAgo: '3 weeks ago' },
  { id: 'ae-4', name: 'Mariam Al-Marzooqi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 4, text: '“I appreciate that everything is clearly arranged.”', timeAgo: '1 month ago' },
  { id: 'ae-5', name: 'Khalid Al-Shehhi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The design gives a premium feeling honestly.”', timeAgo: '2 months ago' },
  { id: 'ae-6', name: 'Latifa Al-Muhairi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“Everything has been straightforward so far.”', timeAgo: '3 months ago' },
  { id: 'ae-7', name: 'Hamad Al-Dhaheri', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The transaction history section is easy to understand.”', timeAgo: '4 months ago' },
  { id: 'ae-8', name: 'Fatima Al-Rumaithi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 4, text: '“I expected hidden stress but didn’t really encounter any.”', timeAgo: '5 months ago' },
  { id: 'ae-9', name: 'Saeed Al-Mazrouei', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The app feels very modern.”', timeAgo: '6 months ago' },
  { id: 'ae-10', name: 'Shaikha Al-Shamsi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“So far the consistency has been decent.”', timeAgo: '7 months ago' },
  { id: 'ae-11', name: 'Zayed Al-Neyadi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The support team answered my questions faster than expected.”', timeAgo: '8 months ago' },
  { id: 'ae-12', name: 'Reem Al-Kailani', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 4, text: '“I’m still monitoring things carefully.”', timeAgo: '9 months ago' },
  { id: 'ae-13', name: 'Mansoor Al-Hammadi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 4, text: '“The platform feels easier than most others I’ve tested.”', timeAgo: '10 months ago' },
  { id: 'ae-14', name: 'Sarah Al-Mulla', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“I honestly didn’t expect to like the interface this much.”', timeAgo: '11 months ago' },
  { id: 'ae-15', name: 'Youssef Al-Zaabi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The mobile version feels smooth.”', timeAgo: '1 year ago' },
  { id: 'ae-16', name: 'Mona Al-Sayegh', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“I appreciate how responsive everything feels.”', timeAgo: '1 year ago' },
  { id: 'ae-17', name: 'Adel Al-Blooshi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 4, text: '“It’s one of the cleaner dashboards I’ve seen.”', timeAgo: '1 year ago' },
  { id: 'ae-18', name: 'Hind Al-Ketbi', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“I’ve had no issues navigating around the app.”', timeAgo: '1 year ago' },
  { id: 'ae-19', name: 'Sultan Al-Hosani', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“The simplicity makes a big difference honestly.”', timeAgo: '2 years ago' },
  { id: 'ae-20', name: 'Hessa Al-Ghurair', countryCode: 'AE', countryName: 'United Arab Emirates', rating: 5, text: '“A very solid platform with intuitive menus.”', timeAgo: '2 years ago' },

  // Canada (20)
  { id: 'ca-1', name: 'Emma Tremblay', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The experience has been smooth from the start.”', timeAgo: '2 days ago' },
  { id: 'ca-2', name: 'William Roy', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“I like how lightweight the app feels.”', timeAgo: '1 week ago' },
  { id: 'ca-3', name: 'Olivia Gagnon', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The registration process took almost no time.”', timeAgo: '3 weeks ago' },
  { id: 'ca-4', name: 'Benjamin Cote', countryCode: 'CA', countryName: 'Canada', rating: 4, text: '“I’m impressed but still careful.”', timeAgo: '1 month ago' },
  { id: 'ca-5', name: 'Sophia Levesque', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The support quality stood out to me.”', timeAgo: '2 months ago' },
  { id: 'ca-6', name: 'Oliver Gauthier', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The layout makes sense immediately.”', timeAgo: '3 months ago' },
  { id: 'ca-7', name: 'Ava Fortin', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“I expected confusion but didn’t experience any.”', timeAgo: '4 months ago' },
  { id: 'ca-8', name: 'Lucas Morin', countryCode: 'CA', countryName: 'Canada', rating: 4, text: '“The app gives a trustworthy first impression.”', timeAgo: '5 months ago' },
  { id: 'ca-9', name: 'Charlotte Lavoie', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“Everything about the experience feels polished.”', timeAgo: '6 months ago' },
  { id: 'ca-10', name: 'Noah Pelletier', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The navigation is very straightforward.”', timeAgo: '7 months ago' },
  { id: 'ca-11', name: 'Amelia Belanger', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“I’ve had a calm experience using it so far.”', timeAgo: '8 months ago' },
  { id: 'ca-12', name: 'Nathan Bouchard', countryCode: 'CA', countryName: 'Canada', rating: 4, text: '“The interface is surprisingly beginner friendly.”', timeAgo: '9 months ago' },
  { id: 'ca-13', name: 'Chloe Simard', countryCode: 'CA', countryName: 'Canada', rating: 4, text: '“The app doesn’t overload you with unnecessary things.”', timeAgo: '10 months ago' },
  { id: 'ca-14', name: 'Jacob Girard', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“I appreciate how quickly transactions update.”', timeAgo: '11 months ago' },
  { id: 'ca-15', name: 'Ella Cloutier', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“I honestly thought the hype was exaggerated at first.”', timeAgo: '1 year ago' },
  { id: 'ca-16', name: 'Logan Hebert', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The customer support was patient with me.”', timeAgo: '1 year ago' },
  { id: 'ca-17', name: 'Abigail Fournier', countryCode: 'CA', countryName: 'Canada', rating: 4, text: '“The app feels stable during use.”', timeAgo: '1 year ago' },
  { id: 'ca-18', name: 'Ethan Caron', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“I’ve seen worse platforms honestly.”', timeAgo: '1 year ago' },
  { id: 'ca-19', name: 'Maya Ouellet', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The clean design is one of my favorite things.”', timeAgo: '2 years ago' },
  { id: 'ca-20', name: 'Liam MacDonald', countryCode: 'CA', countryName: 'Canada', rating: 5, text: '“The experience has been decent overall.”', timeAgo: '2 years ago' },

  // Switzerland (20)
  { id: 'ch-1', name: 'Thomas Keller', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“I still observe before making bigger decisions.”', timeAgo: '2 days ago' },
  { id: 'ch-2', name: 'Anna Müller', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“Everything works smoothly on mobile.”', timeAgo: '1 week ago' },
  { id: 'ch-3', name: 'Beat Meier', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The app feels easier than expected.”', timeAgo: '3 weeks ago' },
  { id: 'ch-4', name: 'Sarah Schmid', countryCode: 'CH', countryName: 'Switzerland', rating: 4, text: '“I appreciate the simplicity of the dashboard.”', timeAgo: '1 month ago' },
  { id: 'ch-5', name: 'Daniel Weber', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The transaction flow is smooth every time.”', timeAgo: '2 months ago' },
  { id: 'ch-6', name: 'Laura Brunner', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“I thought there would be hidden stress somewhere.”', timeAgo: '3 months ago' },
  { id: 'ch-7', name: 'Michael Berger', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The interface looks professionally done.”', timeAgo: '4 months ago' },
  { id: 'ch-8', name: 'Sandra Frei', countryCode: 'CH', countryName: 'Switzerland', rating: 4, text: '“The app experience has been comfortable so far.”', timeAgo: '5 months ago' },
  { id: 'ch-9', name: 'Urs Gasser', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“I’m waiting to see long-term consistency.”', timeAgo: '6 months ago' },
  { id: 'ch-10', name: 'Christine Koch', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The onboarding process was surprisingly easy.”', timeAgo: '7 months ago' },
  { id: 'ch-11', name: 'Marc Dubois', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The support response speed impressed me.”', timeAgo: '8 months ago' },
  { id: 'ch-12', name: 'Elodie Martin', countryCode: 'CH', countryName: 'Switzerland', rating: 4, text: '“The platform feels user friendly.”', timeAgo: '9 months ago' },
  { id: 'ch-13', name: 'Jean-Pierre Favre', countryCode: 'CH', countryName: 'Switzerland', rating: 4, text: '“The experience has been better than expected.”', timeAgo: '10 months ago' },
  { id: 'ch-14', name: 'Celine Moret', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The app doesn’t feel cluttered.”', timeAgo: '11 months ago' },
  { id: 'ch-15', name: 'Alessandro Bianchi', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“Everything feels properly optimized.”', timeAgo: '1 year ago' },
  { id: 'ch-16', name: 'Giulia Bernasconi', countryCode: 'CH', countryName: 'Switzerland', rating: 4, text: '“The dashboard layout is clean.”', timeAgo: '1 year ago' },
  { id: 'ch-17', name: 'Luca Fontana', countryCode: 'CH', countryName: 'Switzerland', rating: 4, text: '“I’m still cautious naturally.”', timeAgo: '1 year ago' },
  { id: 'ch-18', name: 'Francesca Colombo', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The experience has been smooth enough for me.”', timeAgo: '1 year ago' },
  { id: 'ch-19', name: 'Reto Sutter', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The support team actually listens.”', timeAgo: '2 years ago' },
  { id: 'ch-20', name: 'Karin Wenger', countryCode: 'CH', countryName: 'Switzerland', rating: 5, text: '“The app performance has been reliable.”', timeAgo: '2 years ago' },

  // Spain (20)
  { id: 'es-1', name: 'Alejandro Garcia', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I honestly expected the withdrawals to be difficult.”', timeAgo: '2 days ago' },
  { id: 'es-2', name: 'Maria Rodriguez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The experience is very straightforward.”', timeAgo: '1 week ago' },
  { id: 'es-3', name: 'Daniel Martin', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I joined because I saw a close friend using it.”', timeAgo: '3 weeks ago' },
  { id: 'es-4', name: 'Lucia Gonzalez', countryCode: 'ES', countryName: 'Spain', rating: 4, text: '“The support team is actually helpful.”', timeAgo: '1 month ago' },
  { id: 'es-5', name: 'David Fernandez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I’m still observing but I like what I see.”', timeAgo: '2 months ago' },
  { id: 'es-6', name: 'Paula Lopez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The app feels much smoother than I thought.”', timeAgo: '3 months ago' },
  { id: 'es-7', name: 'Javier Martinez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“Everything looks clean and well organized.”', timeAgo: '4 months ago' },
  { id: 'es-8', name: 'Sara Sanchez', countryCode: 'ES', countryName: 'Spain', rating: 4, text: '“The dashboard makes it easy to track progress.”', timeAgo: '5 months ago' },
  { id: 'es-9', name: 'Adrian Perez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I’ve had a very calm experience so far.”', timeAgo: '6 months ago' },
  { id: 'es-10', name: 'Irene Gomez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The verification was faster than expected.”', timeAgo: '7 months ago' },
  { id: 'es-11', name: 'Carlos Martin', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The interface flows very well.”', timeAgo: '8 months ago' },
  { id: 'es-12', name: 'Elena Ruiz', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I appreciate the lack of unnecessary clutter.”', timeAgo: '9 months ago' },
  { id: 'es-13', name: 'Marcos Diaz', countryCode: 'ES', countryName: 'Spain', rating: 4, text: '“The app performance has been stable.”', timeAgo: '10 months ago' },
  { id: 'es-14', name: 'Alba Hernandez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I honestly thought it would be more complicated.”', timeAgo: '11 months ago' },
  { id: 'es-15', name: 'Hugo Alvarez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The customer service actually responds on time.”', timeAgo: '1 year ago' },
  { id: 'es-16', name: 'Sofia Torres', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The experience feels professional.”', timeAgo: '1 year ago' },
  { id: 'es-17', name: 'Diego Ruiz', countryCode: 'ES', countryName: 'Spain', rating: 4, text: '“I’m happy with how easy it is to navigate.”', timeAgo: '1 year ago' },
  { id: 'es-18', name: 'Marta Moreno', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“Everything responded correctly during signup.”', timeAgo: '1 year ago' },
  { id: 'es-19', name: 'Pablo Jimenez', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“The app feels reliable for daily use.”', timeAgo: '2 years ago' },
  { id: 'es-20', name: 'Carmen Muñoz', countryCode: 'ES', countryName: 'Spain', rating: 5, text: '“I’m glad I gave it a try finally.”', timeAgo: '2 years ago' },

  // Italy (20)
  { id: 'it-1', name: 'Francesco Ferrari', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“The ROI is consistent and the interface is very professional.”', timeAgo: '2 days ago' },
  { id: 'it-2', name: 'Giulia Russo', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“CGA Trades has transformed how I manage my digital assets.”', timeAgo: '1 week ago' },
  { id: 'it-3', name: 'Alessandro Marino', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Fast withdrawals and great support. The premium plan is a game changer.”', timeAgo: '3 weeks ago' },
  { id: 'it-4', name: 'Sofia Bianchi', countryCode: 'IT', countryName: 'Italy', rating: 4, text: '“Seamless experience from signup to my first harvest.”', timeAgo: '1 month ago' },
  { id: 'it-5', name: 'Andrea Bruno', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“The security protocols give me peace of mind.”', timeAgo: '2 months ago' },
  { id: 'it-6', name: 'Alice Gallo', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Impressive yields and very transparent operations.”', timeAgo: '3 months ago' },
  { id: 'it-7', name: 'Lorenzo Costa', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Good platform for institutional grade returns.”', timeAgo: '4 months ago' },
  { id: 'it-8', name: 'Emma Giordano', countryCode: 'IT', countryName: 'Italy', rating: 4, text: '“CGA Trades is the future of wealth management.”', timeAgo: '5 months ago' },
  { id: 'it-9', name: 'Mattia Rizzo', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“The regular plan is perfect for beginners.”', timeAgo: '6 months ago' },
  { id: 'it-10', name: 'Giorgia Lombardi', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Exceptional service and very rewarding ROI clusters.”', timeAgo: '7 months ago' },
  { id: 'it-11', name: 'Gabriele Moretti', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Finally a platform that delivers on its promises.”', timeAgo: '8 months ago' },
  { id: 'it-12', name: 'Chiara Barberis', countryCode: 'IT', countryName: 'Italy', rating: 4, text: '“The user experience is premium. Everything works.”', timeAgo: '9 months ago' },
  { id: 'it-13', name: 'Tommaso Mancini', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Reliable and secure node processes.”', timeAgo: '10 months ago' },
  { id: 'it-14', name: 'Sara Barbieri', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Great for long term wealth building.”', timeAgo: '11 months ago' },
  { id: 'it-15', name: 'Riccardo Fontana', countryCode: 'IT', countryName: 'Italy', rating: 4, text: '“Excellent support team and guided onboarding.”', timeAgo: '1 year ago' },
  { id: 'it-16', name: 'Beatrice Santoro', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“The neural trading engine is truly next-gen.”', timeAgo: '1 year ago' },
  { id: 'it-17', name: 'Leonardo Mariani', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Consistent daily earnings. Best decision.”', timeAgo: '1 year ago' },
  { id: 'it-18', name: 'Gaia Marini', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Elite interface for elite investors. Highly recommend.”', timeAgo: '1 year ago' },
  { id: 'it-19', name: 'Federico Rinaldi', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Setting new standards in asset management.”', timeAgo: '2 years ago' },
  { id: 'it-20', name: 'Noemi Villa', countryCode: 'IT', countryName: 'Italy', rating: 5, text: '“Elite security and elite performance. Best in market.”', timeAgo: '2 years ago' },

  // Portugal (20)
  { id: 'pt-1', name: 'João Silva', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“The loading speed is one of the first things I noticed.”', timeAgo: '2 days ago' },
  { id: 'pt-2', name: 'Maria Santos', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“The onboarding process was completely frictionless.”', timeAgo: '1 week ago' },
  { id: 'pt-3', name: 'Francisco Ferreira', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“The interface is beautiful and extremely fast.”', timeAgo: '3 weeks ago' },
  { id: 'pt-4', name: 'Ana Pereira', countryCode: 'PT', countryName: 'Portugal', rating: 4, text: '“A well-polished product that works flawlessly.”', timeAgo: '1 month ago' },
  { id: 'pt-5', name: 'Pedro Oliveira', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Highly intuitive layout and stellar security.”', timeAgo: '2 months ago' },
  { id: 'pt-6', name: 'Sofia Costa', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“The charts are crisp and updating in real-time.”', timeAgo: '3 months ago' },
  { id: 'pt-7', name: 'Diogo Rodrigues', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Cleanest visual design of any dashboard I have seen.”', timeAgo: '4 months ago' },
  { id: 'pt-8', name: 'Inês Martins', countryCode: 'PT', countryName: 'Portugal', rating: 4, text: '“Great mobile optimization for on-the-go checks.”', timeAgo: '5 months ago' },
  { id: 'pt-9', name: 'Miguel Jesus', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Highly recommended for passive asset growth.”', timeAgo: '6 months ago' },
  { id: 'pt-10', name: 'Mariana Pinto', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“The node execution runs exactly as scheduled.”', timeAgo: '7 months ago' },
  { id: 'pt-11', name: 'Afonso Rebelo', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Exceptional UI fluidity across both web and mobile.”', timeAgo: '8 months ago' },
  { id: 'pt-12', name: 'Beatriz Neves', countryCode: 'PT', countryName: 'Portugal', rating: 4, text: '“Customer support answered my questions with detailed responses.”', timeAgo: '9 months ago' },
  { id: 'pt-13', name: 'Rodrigo Cruz', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Very direct and no-nonsense registration flow.”', timeAgo: '10 months ago' },
  { id: 'pt-14', name: 'Leonor Machado', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Extremely professional presentation of metrics.”', timeAgo: '11 months ago' },
  { id: 'pt-15', name: 'Tiago Rocha', countryCode: 'PT', countryName: 'Portugal', rating: 4, text: '“I was cautious initially but the transparency won me over.”', timeAgo: '1 year ago' },
  { id: 'pt-16', name: 'Carolina Fonseca', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Fantastic system stability even during peak hours.”', timeAgo: '1 year ago' },
  { id: 'pt-17', name: 'Tomás Ribeiro', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“An incredible upgrade compared to my previous platform.”', timeAgo: '1 year ago' },
  { id: 'pt-18', name: 'Margarida Carvalho', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Fast confirmation on deposits and seamless tracking.”', timeAgo: '1 year ago' },
  { id: 'pt-19', name: 'Guilherme Lopes', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“The security features are incredibly robust.”', timeAgo: '2 years ago' },
  { id: 'pt-20', name: 'Francisca Teixeira', countryCode: 'PT', countryName: 'Portugal', rating: 5, text: '“Everything was smooth, from deposit to daily accrual.”', timeAgo: '2 years ago' },

  // Kuwait (20)
  { id: 'kw-1', name: 'Fahad Al-Mutairi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Exceptional stability and impressive execution speed.”', timeAgo: '2 days ago' },
  { id: 'kw-2', name: 'Noura Al-Otaibi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“The premium node activation has been highly rewarding.”', timeAgo: '1 week ago' },
  { id: 'kw-3', name: 'Abdulrahman Al-Fadhli', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“A clean and very modern interface that is easy to navigate.”', timeAgo: '3 weeks ago' },
  { id: 'kw-4', name: 'Fatima Al-Shammari', countryCode: 'KW', countryName: 'Kuwait', rating: 4, text: '“No hidden fees or unexpected delays, very honest platform.”', timeAgo: '1 month ago' },
  { id: 'kw-5', name: 'Abdullah Al-Ajmi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Customer care response is fast and helpful.”', timeAgo: '2 months ago' },
  { id: 'kw-6', name: 'Maryam Al-Azmi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Extremely streamlined and aesthetically pleasing design.”', timeAgo: '3 months ago' },
  { id: 'kw-7', name: 'Mubarak Al-Rashidi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“The performance graphs are clean and easy to interpret.”', timeAgo: '4 months ago' },
  { id: 'kw-8', name: 'Sarah Al-Anzi', countryCode: 'KW', countryName: 'Kuwait', rating: 4, text: '“A secure platform that does exactly what it promises.”', timeAgo: '5 months ago' },
  { id: 'kw-9', name: 'Yousef Al-Harbi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Onboarding was fast and verification was automated.”', timeAgo: '6 months ago' },
  { id: 'kw-10', name: 'Dana Al-Khaldi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Excellent features that outshine other platforms.”', timeAgo: '7 months ago' },
  { id: 'kw-11', name: 'Bader Al-Dousari', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Very stable app on both mobile and desktop views.”', timeAgo: '8 months ago' },
  { id: 'kw-12', name: 'Reem Al-Kandari', countryCode: 'KW', countryName: 'Kuwait', rating: 4, text: '“Great system documentation and useful guides.”', timeAgo: '9 months ago' },
  { id: 'kw-13', name: 'Jassem Al-Shatti', countryCode: 'KW', countryName: 'Kuwait', rating: 4, text: '“Highly reliable daily execution updates.”', timeAgo: '10 months ago' },
  { id: 'kw-14', name: 'Dalal Al-Ghanim', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“The interface is polished and premium.”', timeAgo: '11 months ago' },
  { id: 'kw-15', name: 'Ali Al-Farsi', countryCode: 'KW', countryName: 'Kuwait', rating: 4, text: '“I have recommended this platform to my entire circle.”', timeAgo: '1 year ago' },
  { id: 'kw-16', name: 'Hessa Al-Saeed', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Clear and detailed transaction tracking.”', timeAgo: '1 year ago' },
  { id: 'kw-17', name: 'Khaled Al-Hajri', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Everything is optimized for rapid execution.”', timeAgo: '1 year ago' },
  { id: 'kw-18', name: 'Lulwa Al-Mulla', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Very professional setup with high-tier security.”', timeAgo: '1 year ago' },
  { id: 'kw-19', name: 'Meshari Al-Enezi', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Fabulous performance and reliable support.”', timeAgo: '2 years ago' },
  { id: 'kw-20', name: 'Aisha Al-Bader', countryCode: 'KW', countryName: 'Kuwait', rating: 5, text: '“Extremely happy with the smooth operations.”', timeAgo: '2 years ago' },
];

export interface Investor {
  id: string;
  name: string;
  countryCode: string;
  countryName: string;
  amount: number;
  dailyRoi: number;
  rank: number;
  photoURL?: string;
}

export const TOP_INVESTORS: Investor[] = [
  { 
    id: 'inv-1', 
    name: 'Lord Sterling', 
    countryCode: 'GB', 
    countryName: 'UK', 
    amount: 3800000, 
    dailyRoi: 110200, 
    rank: 1,
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-2', 
    name: 'Olu Jide', 
    countryCode: 'NG', 
    countryName: 'Nigeria', 
    amount: 3250000, 
    dailyRoi: 94250, 
    rank: 2,
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-3', 
    name: 'Chen Wei', 
    countryCode: 'CN', 
    countryName: 'China', 
    amount: 2900000, 
    dailyRoi: 84100, 
    rank: 3,
    photoURL: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-4', 
    name: 'Marcus Tan', 
    countryCode: 'SG', 
    countryName: 'Singapore', 
    amount: 2100000, 
    dailyRoi: 60900, 
    rank: 4,
    photoURL: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-5', 
    name: 'Sarah Miller', 
    countryCode: 'US', 
    countryName: 'US', 
    amount: 1850000, 
    dailyRoi: 53650, 
    rank: 5,
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-6', 
    name: 'Juma Hassan', 
    countryCode: 'TZ', 
    countryName: 'Tanzania', 
    amount: 1200000, 
    dailyRoi: 34800, 
    rank: 6,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juma'
  },
  { 
    id: 'inv-7', 
    name: 'Thabo Ndlovu', 
    countryCode: 'ZA', 
    countryName: 'South Africa', 
    amount: 850000, 
    dailyRoi: 22950, 
    rank: 7,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=thabo'
  },
  { 
    id: 'inv-8', 
    name: 'Wong Ka-shing', 
    countryCode: 'HK', 
    countryName: 'Hong Kong', 
    amount: 620000, 
    dailyRoi: 16740, 
    rank: 8,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wong'
  },
  { 
    id: 'inv-9', 
    name: 'Lindiwe Dlamini', 
    countryCode: 'ZA', 
    countryName: 'South Africa', 
    amount: 520000, 
    dailyRoi: 14040, 
    rank: 9,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lindiwe'
  },
  { 
    id: 'inv-10', 
    name: 'Ayo Moses', 
    countryCode: 'NG', 
    countryName: 'Nigeria', 
    amount: 480000, 
    dailyRoi: 12960, 
    rank: 10,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=moses'
  },
  { id: 'inv-11', name: 'Elena Rossi', countryCode: 'IT', countryName: 'Italy', amount: 450000, dailyRoi: 12150, rank: 11, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena' },
  { id: 'inv-12', name: 'Hiroshi Tanaka', countryCode: 'JP', countryName: 'Japan', amount: 425000, dailyRoi: 11475, rank: 12, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hiroshi' },
  { id: 'inv-13', name: 'Amira Mansour', countryCode: 'EG', countryName: 'Egypt', amount: 410000, dailyRoi: 11070, rank: 13, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amira' },
  { id: 'inv-14', name: 'Lukas Fischer', countryCode: 'DE', countryName: 'Germany', amount: 395000, dailyRoi: 10665, rank: 14, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lukas' },
  { id: 'inv-15', name: 'Sofia Silva', countryCode: 'BR', countryName: 'Brazil', amount: 380000, dailyRoi: 10260, rank: 15, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sofia' },
  { id: 'inv-16', name: 'Liam O\'Connor', countryCode: 'IE', countryName: 'Ireland', amount: 365000, dailyRoi: 9855, rank: 16, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liam' },
  { id: 'inv-17', name: 'Alya Volkova', countryCode: 'RU', countryName: 'Russia', amount: 350000, dailyRoi: 9450, rank: 17, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alya' },
  { id: 'inv-18', name: 'Mateo Garcia', countryCode: 'ES', countryName: 'Spain', amount: 340000, dailyRoi: 9180, rank: 18, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mateo' },
  { id: 'inv-19', name: 'Chloe Dubois', countryCode: 'FR', countryName: 'France', amount: 330000, dailyRoi: 8910, rank: 19, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chloe' },
  { id: 'inv-20', name: 'Arjun Gupta', countryCode: 'IN', countryName: 'India', amount: 320000, dailyRoi: 8640, rank: 20, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun' },
  { id: 'inv-21', name: 'Isabella Hernandez', countryCode: 'MX', countryName: 'Mexico', amount: 310000, dailyRoi: 8370, rank: 21, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=isabella' },
  { id: 'inv-22', name: 'Noah Wilson', countryCode: 'CA', countryName: 'Canada', amount: 300000, dailyRoi: 8100, rank: 22, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=noah' },
  { id: 'inv-23', name: 'Mia Andersen', countryCode: 'DK', countryName: 'Denmark', amount: 290000, dailyRoi: 7830, rank: 23, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mia' },
  { id: 'inv-24', name: 'Oliver Smith', countryCode: 'AU', countryName: 'Australia', amount: 280000, dailyRoi: 7560, rank: 24, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=oliver' },
  { id: 'inv-25', name: 'Fatima Al-Said', countryCode: 'AE', countryName: 'UAE', amount: 275000, dailyRoi: 7425, rank: 25, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima' },
  { id: 'inv-26', name: 'Sven Berg', countryCode: 'SE', countryName: 'Sweden', amount: 270000, dailyRoi: 7290, rank: 26, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sven' },
  { id: 'inv-27', name: 'Ji-won Kim', countryCode: 'KR', countryName: 'South Korea', amount: 265000, dailyRoi: 7155, rank: 27, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jiwon' },
  { id: 'inv-28', name: 'Ahmed Hassan', countryCode: 'SA', countryName: 'Saudi Arabia', amount: 260000, dailyRoi: 7020, rank: 28, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed' },
  { id: 'inv-29', name: 'Yuki Nakamura', countryCode: 'JP', countryName: 'Japan', amount: 255000, dailyRoi: 6885, rank: 29, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yuki' },
  { id: 'inv-30', name: 'Larissa Santos', countryCode: 'BR', countryName: 'Brazil', amount: 250000, dailyRoi: 6750, rank: 30, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=larissa' },
  { id: 'inv-31', name: 'Priya Sharma', countryCode: 'IN', countryName: 'India', amount: 245000, dailyRoi: 6615, rank: 31, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya' },
  { id: 'inv-32', name: 'Thomas Mueller', countryCode: 'DE', countryName: 'Germany', amount: 240000, dailyRoi: 6480, rank: 32, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=thomas' },
  { id: 'inv-33', name: 'Emma Johnson', countryCode: 'US', countryName: 'USA', amount: 235000, dailyRoi: 6345, rank: 33, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma' },
  { id: 'inv-34', name: 'Gabriel Martinez', countryCode: 'ES', countryName: 'Spain', amount: 230000, dailyRoi: 6210, rank: 34, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=gabriel' },
  { id: 'inv-35', name: 'Hanna Lindholm', countryCode: 'FI', countryName: 'Finland', amount: 225000, dailyRoi: 6075, rank: 35, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hanna' },
  { id: 'inv-36', name: 'Omer Farooq', countryCode: 'PK', countryName: 'Pakistan', amount: 220000, dailyRoi: 5940, rank: 36, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=omer' },
  { id: 'inv-37', name: 'Nikoletta Pappas', countryCode: 'GR', countryName: 'Greece', amount: 215000, dailyRoi: 5805, rank: 37, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nikoletta' },
  { id: 'inv-38', name: 'Zoltan Nagy', countryCode: 'HU', countryName: 'Hungary', amount: 210000, dailyRoi: 5670, rank: 38, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zoltan' },
  { id: 'inv-39', name: 'Anikó Kovács', countryCode: 'HU', countryName: 'Hungary', amount: 205000, dailyRoi: 5535, rank: 39, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aniko' },
  { id: 'inv-40', name: 'Karel Novak', countryCode: 'CZ', countryName: 'Czech Republic', amount: 200000, dailyRoi: 5400, rank: 40, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karel' },
  { id: 'inv-41', name: 'Marta Nowak', countryCode: 'PL', countryName: 'Poland', amount: 195000, dailyRoi: 5265, rank: 41, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marta' },
  { id: 'inv-42', name: 'Sven Gustafsson', countryCode: 'SE', countryName: 'Sweden', amount: 190000, dailyRoi: 5130, rank: 42, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sven2' },
  { id: 'inv-43', name: 'Elena Petrova', countryCode: 'BG', countryName: 'Bulgaria', amount: 185000, dailyRoi: 4995, rank: 43, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena2' },
  { id: 'inv-44', name: 'Rafael Silva', countryCode: 'PT', countryName: 'Portugal', amount: 180000, dailyRoi: 4860, rank: 44, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rafael' },
  { id: 'inv-45', name: 'Ingrid Meyer', countryCode: 'CH', countryName: 'Switzerland', amount: 175000, dailyRoi: 4725, rank: 45, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ingrid' },
  { id: 'inv-46', name: 'Hans De Jong', countryCode: 'NL', countryName: 'Netherlands', amount: 170000, dailyRoi: 4590, rank: 46, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hans' },
  { id: 'inv-47', name: 'Anna Lindgren', countryCode: 'NO', countryName: 'Norway', amount: 165000, dailyRoi: 4455, rank: 47, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anna' },
  { id: 'inv-48', name: 'Paul Clarke', countryCode: 'NZ', countryName: 'New Zealand', amount: 160000, dailyRoi: 4320, rank: 48, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=paul' },
  { id: 'inv-49', name: 'Dimitri Ivanov', countryCode: 'UA', countryName: 'Ukraine', amount: 155000, dailyRoi: 4185, rank: 49, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dimitri' },
  { id: 'inv-50', name: 'Fatima Zahra', countryCode: 'MA', countryName: 'Morocco', amount: 150000, dailyRoi: 4050, rank: 50, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima2' },
  { id: 'inv-51', name: 'Kenji Sato', countryCode: 'JP', countryName: 'Japan', amount: 145000, dailyRoi: 3915, rank: 51, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kenji' },
  { id: 'inv-52', name: 'Lucia Romano', countryCode: 'IT', countryName: 'Italy', amount: 140000, dailyRoi: 3780, rank: 52, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucia' },
  { id: 'inv-53', name: 'Marko Jovic', countryCode: 'RS', countryName: 'Serbia', amount: 135000, dailyRoi: 3645, rank: 53, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marko' },
  { id: 'inv-54', name: 'Sonia Gupta', countryCode: 'IN', countryName: 'India', amount: 130000, dailyRoi: 3510, rank: 54, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sonia' },
  { id: 'inv-55', name: 'Anders Nyman', countryCode: 'SE', countryName: 'Sweden', amount: 125000, dailyRoi: 3375, rank: 55, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anders' },
  { id: 'inv-56', name: 'Tariq Al-Farsi', countryCode: 'OM', countryName: 'Oman', amount: 120000, dailyRoi: 3240, rank: 56, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tariq' },
  { id: 'inv-57', name: 'Mei Ling', countryCode: 'CN', countryName: 'China', amount: 115000, dailyRoi: 3105, rank: 57, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meiling' },
  { id: 'inv-58', name: 'Rohan Deshmukh', countryCode: 'IN', countryName: 'India', amount: 110000, dailyRoi: 2970, rank: 58, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rohan' },
  { id: 'inv-59', name: 'Carmen Rojas', countryCode: 'CL', countryName: 'Chile', amount: 105000, dailyRoi: 2835, rank: 59, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carmen' },
  { id: 'inv-60', name: 'Klaus Schmidt', countryCode: 'AT', countryName: 'Austria', amount: 100000, dailyRoi: 2700, rank: 60, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=klaus' },
  { id: 'inv-61', name: 'Ji-seon Lee', countryCode: 'KR', countryName: 'South Korea', amount: 95000, dailyRoi: 2565, rank: 61, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jiseon' },
  { id: 'inv-62', name: 'Omar Bakri', countryCode: 'LB', countryName: 'Lebanon', amount: 90000, dailyRoi: 2430, rank: 62, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=omar' },
  { id: 'inv-63', name: 'Hélène Leroy', countryCode: 'BE', countryName: 'Belgium', amount: 85000, dailyRoi: 2295, rank: 63, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=helene' },
  { id: 'inv-64', name: 'Pavel Kuznetsov', countryCode: 'RU', countryName: 'Russia', amount: 80000, dailyRoi: 2160, rank: 64, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pavel' },
  { id: 'inv-65', name: 'Sandra Bullock', countryCode: 'US', countryName: 'USA', amount: 75000, dailyRoi: 2025, rank: 65, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sandra' },
  { id: 'inv-66', name: 'Diego Torres', countryCode: 'AR', countryName: 'Argentina', amount: 70000, dailyRoi: 1890, rank: 66, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diego' },
  { id: 'inv-67', name: 'Fatima Jinnah', countryCode: 'PK', countryName: 'Pakistan', amount: 65000, dailyRoi: 1755, rank: 67, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima3' },
  { id: 'inv-68', name: 'Lars Nielsen', countryCode: 'DK', countryName: 'Denmark', amount: 60000, dailyRoi: 1620, rank: 68, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lars' },
  { id: 'inv-69', name: 'Emma Wilson', countryCode: 'AU', countryName: 'Australia', amount: 55000, dailyRoi: 1485, rank: 69, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma2' },
  { id: 'inv-70', name: 'Chen Hao', countryCode: 'CN', countryName: 'China', amount: 50000, dailyRoi: 1350, rank: 70, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chenhao' },
  { id: 'inv-71', name: 'Sara Costa', countryCode: 'PT', countryName: 'Portugal', amount: 48000, dailyRoi: 1296, rank: 71, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sara' },
  { id: 'inv-72', name: 'Oksana Shevchenko', countryCode: 'UA', countryName: 'Ukraine', amount: 46000, dailyRoi: 1242, rank: 72, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=oksana' },
  { id: 'inv-73', name: 'Matteo Colombo', countryCode: 'IT', countryName: 'Italy', amount: 44000, dailyRoi: 1188, rank: 73, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=matteo2' },
  { id: 'inv-74', name: 'Isabelle Maes', countryCode: 'BE', countryName: 'Belgium', amount: 42000, dailyRoi: 1134, rank: 74, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=isabelle' },
  { id: 'inv-75', name: 'David Smith', countryCode: 'UK', countryName: 'UK', amount: 40000, dailyRoi: 1080, rank: 75, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david' },
  { id: 'inv-76', name: 'Ayo Balogun', countryCode: 'NG', countryName: 'Nigeria', amount: 38000, dailyRoi: 1026, rank: 76, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ayo' },
  { id: 'inv-77', name: 'Elena Koroleva', countryCode: 'RU', countryName: 'Russia', amount: 36000, dailyRoi: 972, rank: 77, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena3' },
  { id: 'inv-78', name: 'Marek Jankowski', countryCode: 'PL', countryName: 'Poland', amount: 34000, dailyRoi: 918, rank: 78, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marek' },
  { id: 'inv-79', name: 'Yuki Watanabe', countryCode: 'JP', countryName: 'Japan', amount: 32000, dailyRoi: 864, rank: 79, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yuki2' },
  { id: 'inv-80', name: 'Sophia Chen', countryCode: 'CA', countryName: 'Canada', amount: 30000, dailyRoi: 810, rank: 80, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sophia' },
  { id: 'inv-81', name: 'Lucas Dubois', countryCode: 'FR', countryName: 'France', amount: 28000, dailyRoi: 756, rank: 81, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucas2' },
  { id: 'inv-82', name: 'Hanna Bjork', countryCode: 'NO', countryName: 'Norway', amount: 26000, dailyRoi: 702, rank: 82, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hanna2' },
  { id: 'inv-83', name: 'Fatih Terim', countryCode: 'TR', countryName: 'Turkey', amount: 24000, dailyRoi: 648, rank: 83, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatih' },
  { id: 'inv-84', name: 'Leyla Gunes', countryCode: 'TR', countryName: 'Turkey', amount: 22000, dailyRoi: 594, rank: 84, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=leyla' },
  { id: 'inv-85', name: 'Ivan Horvat', countryCode: 'HR', countryName: 'Croatia', amount: 20000, dailyRoi: 540, rank: 85, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivan' },
  { id: 'inv-86', name: 'Amalie Jensen', countryCode: 'DK', countryName: 'Denmark', amount: 18000, dailyRoi: 486, rank: 86, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amalie' },
  { id: 'inv-87', name: 'Liam Davies', countryCode: 'AU', countryName: 'Australia', amount: 16000, dailyRoi: 432, rank: 87, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liam2' },
  { id: 'inv-88', name: 'Mateo Lopez', countryCode: 'CO', countryName: 'Colombia', amount: 14000, dailyRoi: 378, rank: 88, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mateo3' },
  { id: 'inv-89', name: 'Anya Sharma', countryCode: 'IN', countryName: 'India', amount: 12000, dailyRoi: 324, rank: 89, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anya' },
  { id: 'inv-90', name: 'Koji Yamamoto', countryCode: 'JP', countryName: 'Japan', amount: 10000, dailyRoi: 270, rank: 90, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=koji' },
  { id: 'inv-91', name: 'Elena Dimitrova', countryCode: 'BG', countryName: 'Bulgaria', amount: 9000, dailyRoi: 243, rank: 91, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena4' },
  { id: 'inv-92', name: 'Markus Weber', countryCode: 'AT', countryName: 'Austria', amount: 8000, dailyRoi: 216, rank: 92, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=markus' },
  { id: 'inv-93', name: 'Silvia Conti', countryCode: 'IT', countryName: 'Italy', amount: 7500, dailyRoi: 202, rank: 93, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=silvia' },
  { id: 'inv-94', name: 'Joao Silva', countryCode: 'BR', countryName: 'Brazil', amount: 7000, dailyRoi: 189, rank: 94, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=joao' },
  { id: 'inv-95', name: 'Nathalie Meyer', countryCode: 'CH', countryName: 'Switzerland', amount: 6500, dailyRoi: 175, rank: 95, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nathalie' },
  { id: 'inv-96', name: 'Ole Hansen', countryCode: 'NO', countryName: 'Norway', amount: 6000, dailyRoi: 162, rank: 96, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ole' },
  { id: 'inv-97', name: 'Fatima Al-Khatib', countryCode: 'JO', countryName: 'Jordan', amount: 5500, dailyRoi: 148, rank: 97, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima4' },
  { id: 'inv-98', name: 'Artem Novikov', countryCode: 'UA', countryName: 'Ukraine', amount: 5000, dailyRoi: 135, rank: 98, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=artem' },
  { id: 'inv-99', name: 'Svenja Mueller', countryCode: 'DE', countryName: 'Germany', amount: 4500, dailyRoi: 121, rank: 99, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=svenja' },
  { id: 'inv-100', name: 'Ali Ahmed', countryCode: 'QA', countryName: 'Qatar', amount: 4000, dailyRoi: 108, rank: 100, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aliahmed' },
];
